# Generated by Django 4.0 on 2021-12-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('liquid', models.FloatField()),
                ('oil', models.FloatField()),
                ('water', models.FloatField()),
                ('wct', models.FloatField()),
            ],
        ),
    ]
